---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install ruby and rubygems.
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - rubygems1.9.1
